apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
  - name: postgres
    image: postgres:latest
    env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_PASSWORD
      value: password      
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: postgres-data
        mountPath: /var/lib/postgresql/data
         

