apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
spec:
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: mzuri/book-service
        ports:
        - containerPort: 8080
